In [1]:
import numpy as np
import pandas as pd

In [126]:
customer_data_2017 = pd.read_csv("final2017.csv", index_col =0)
customer_data_2018 = pd.read_csv("final2018.csv" ,index_col = 0)
customer_data_2019 = pd.read_csv("final2019.csv", index_col = 0)

In [27]:
final_2017 = pd.read_csv("final2017.csv")
final_2018 = pd.read_csv("final2018.csv")
final_2019 = pd.read_csv("final2019.csv")

cust_set_2017 = set(final_2017["customer_id"])
cust_set_2018 = set(final_2018["customer_id"])
cust_set_2019 = set(final_2019["customer_id"])
no_noise_cus_2017 = []
no_noise_cus_2018 = []
no_noise_cus_2019 = []

def data_clean(d,s,o):
    for i in d:
        #using number of months visited
        months = ["jan_4","feb_4","mar_4","apr_4","may_4","jun_4","jul_4","aug_4","sep_4","oct_4", "nov_4", "dec_4" ]
        tot_num_visits = 0
        for mnths in months:
            frame = pd.DataFrame(s.loc[s["customer_id"] == i][mnths])
            if frame.iloc[0][mnths] != 0.0:
                tot_num_visits += 1
        if tot_num_visits < 3: #threshold for months
            o.append(i)


In [28]:
d = cust_set_2017
s = final_2017
o = no_noise_cus_2017
data_clean(d,s,o)

In [29]:
d = cust_set_2018
s = final_2018
o2 = no_noise_cus_2018
data_clean(d,s,o2)

In [30]:
d = cust_set_2019
s = final_2019
o3 = no_noise_cus_2019
data_clean(d,s,o3)

In [14]:
def intersection(lst1, lst2): 
    return list(set(lst1) & set(lst2)) 

In [17]:
remove = intersection(o, intersection(o3,o2))
len(remove)

3086

In [127]:
def Union(lst1, lst2): 
    final_list = list(set(lst1) | set(lst2)) 
    return final_list 

In [128]:
rem = Union(o,Union(o2,o3))

In [129]:
len(rem)

6646

In [182]:
submission_lgbm = pd.read_csv("submissionlgbm.csv",index_col = 0)

In [183]:
submission_lgbm

prob
customer_id          
169212       0.012739
174861       0.016533
198521       0.011391
206454       0.006736
218494       0.329560
...               ...
1177848      0.677111
1249165      0.879916
1284253      0.373209
1308030      0.318757
1326394      0.048402

[10000 rows x 1 columns]

In [184]:
submission_lgbm_new = submission_lgbm.drop(rem)

In [186]:
submission_lgbm_new = submission_lgbm_new.reset_index()

In [189]:
submission_lgbm_new

customer_id      prob
0          169212  0.012739
1          174861  0.016533
2          198521  0.011391
3          206454  0.006736
4          247866  0.007950
...           ...       ...
3349       433006  0.036599
3350       604998  0.006674
3351       726557  0.072661
3352       727203  0.202983
3353       859411  0.006385

[3354 rows x 2 columns]

In [188]:
submission_lgbm_new.to_csv("optimizeprime.csv")

In [130]:
customer_data_2017

gender  birth_year    jan_1  jan_2     jan_3  jan_4    feb_1  \
customer_id                                                                 
169212       female      1980.0     0.00    0.0      0.00    0.0   100.00   
174861       female      1969.0  2160.31    2.0   8731.09    6.0   100.00   
198521         male      1978.0   361.00    1.0   1483.00    3.0  1682.50   
206454         male      1965.0  4954.62    1.0  13716.61    7.0  3630.22   
218494         male      1959.0     0.00    0.0      0.00    0.0     0.00   
...             ...         ...      ...    ...       ...    ...      ...   
1177848      female      1993.0     0.00    0.0      0.00    0.0     0.00   
1249165        male      1988.0     0.00    0.0      0.00    0.0     0.00   
1284253      female      1991.0     0.00    0.0      0.00    0.0     0.00   
1308030        male      1997.0     0.00    0.0      0.00    0.0     0.00   
1326394      female      1997.0     0.00    0.0      0.00    0.0     0.00   

             feb_2     feb_3  feb_4  ...  churn_2  churn_3  churn_4  churn_5  \
customer_id                          ...                                       
169212         0.0   7895.58    3.0  ...      1.0      1.0      0.0      0.0   
174861         0.0   6155.50    3.0  ...      0.0      0.0      0.0      0.0   
198521         1.0   2824.00    3.0  ...      0.0      0.0      0.0      0.0   
206454         2.0  12095.13    6.0  ...      0.0      0.0      0.0      0.0   
218494         0.0      0.00    0.0  ...      0.0      1.0      1.0      1.0   
...            ...       ...    ...  ...      ...      ...      ...      ...   
1177848        0.0      0.00    0.0  ...      1.0      1.0      1.0      1.0   
1249165        0.0      0.00    0.0  ...      1.0      1.0      1.0      1.0   
1284253        0.0      0.00    0.0  ...      1.0      1.0      1.0      1.0   
1308030        0.0      0.00    0.0  ...      1.0      1.0      1.0      1.0   
1326394        0.0      0.00    0.0  ...      1.0      1.0      1.0      1.0   

             churn_6  churn_7  churn_8  churn_9  churn_10  dec_churn  
customer_id                                                           
169212           0.0      0.0      0.0      0.0       0.0        0.0  
174861           0.0      0.0      0.0      0.0       0.0        0.0  
198521           0.0      0.0      0.0      0.0       0.0        0.0  
206454           0.0      0.0      0.0      0.0       0.0        0.0  
218494           1.0      1.0      1.0      1.0       1.0        1.0  
...              ...      ...      ...      ...       ...        ...  
1177848          1.0      1.0      1.0      1.0       1.0        1.0  
1249165          1.0      1.0      1.0      1.0       1.0        1.0  
1284253          1.0      1.0      1.0      1.0       1.0        1.0  
1308030          1.0      1.0      1.0      1.0       1.0        1.0  
1326394          1.0      1.0      1.0      1.0       1.0        1.0  

[10000 rows x 61 columns]

In [131]:
customer_data_2017 = customer_data_2017.drop(rem)
customer_data_2018 = customer_data_2018.drop(rem)
customer_data_2019 = customer_data_2019.drop(rem)

In [132]:
customer_data_2017.to_csv('final2017_filtered.csv', index = False)
customer_data_2018.to_csv('final2018_filtered.csv', index = False)
customer_data_2019.to_csv('final2018_filtered.csv', index = False)

In [133]:
customer_data_2017

gender  birth_year     jan_1  jan_2     jan_3  jan_4     feb_1  \
customer_id                                                                   
169212       female      1980.0      0.00    0.0      0.00    0.0    100.00   
174861       female      1969.0   2160.31    2.0   8731.09    6.0    100.00   
198521         male      1978.0    361.00    1.0   1483.00    3.0   1682.50   
206454         male      1965.0   4954.62    1.0  13716.61    7.0   3630.22   
247866       female      1970.0  28725.77    4.0  39781.03    9.0  19757.50   
...             ...         ...       ...    ...       ...    ...       ...   
433006       female      1985.0      0.00    0.0      0.00    0.0   4502.20   
604998         male      1966.0   3340.00    1.0  15310.77   12.0   6295.00   
726557         male      1994.0   2700.82    1.0   3900.82    2.0    100.00   
727203       female      1993.0    100.00    0.0    400.00    1.0   1493.37   
859411         male      1978.0      0.00    0.0      0.00    0.0      0.00   

             feb_2     feb_3  feb_4  ...  churn_2  churn_3  churn_4  churn_5  \
customer_id                          ...                                       
169212         0.0   7895.58    3.0  ...      1.0      1.0      0.0      0.0   
174861         0.0   6155.50    3.0  ...      0.0      0.0      0.0      0.0   
198521         1.0   2824.00    3.0  ...      0.0      0.0      0.0      0.0   
206454         2.0  12095.13    6.0  ...      0.0      0.0      0.0      0.0   
247866         3.0  23120.05    4.0  ...      0.0      0.0      0.0      0.0   
...            ...       ...    ...  ...      ...      ...      ...      ...   
433006         3.0   5002.42    4.0  ...      0.0      0.0      0.0      0.0   
604998         4.0  28694.88   16.0  ...      0.0      0.0      0.0      0.0   
726557         0.0    325.00    1.0  ...      0.0      0.0      0.0      0.0   
727203         1.0   1493.37    1.0  ...      0.0      0.0      0.0      0.0   
859411         0.0      0.00    0.0  ...      1.0      1.0      1.0      0.0   

             churn_6  churn_7  churn_8  churn_9  churn_10  dec_churn  
customer_id                                                           
169212           0.0      0.0      0.0      0.0       0.0        0.0  
174861           0.0      0.0      0.0      0.0       0.0        0.0  
198521           0.0      0.0      0.0      0.0       0.0        0.0  
206454           0.0      0.0      0.0      0.0       0.0        0.0  
247866           0.0      0.0      0.0      0.0       0.0        0.0  
...              ...      ...      ...      ...       ...        ...  
433006           0.0      1.0      0.0      0.0       0.0        0.0  
604998           0.0      0.0      0.0      0.0       0.0        0.0  
726557           0.0      0.0      0.0      0.0       0.0        1.0  
727203           0.0      1.0      1.0      1.0       1.0        1.0  
859411           0.0      0.0      0.0      0.0       0.0        0.0  

[3354 rows x 61 columns]

In [134]:
customer_data_2017.head()

gender  birth_year     jan_1  jan_2     jan_3  jan_4     feb_1  \
customer_id                                                                   
169212       female      1980.0      0.00    0.0      0.00    0.0    100.00   
174861       female      1969.0   2160.31    2.0   8731.09    6.0    100.00   
198521         male      1978.0    361.00    1.0   1483.00    3.0   1682.50   
206454         male      1965.0   4954.62    1.0  13716.61    7.0   3630.22   
247866       female      1970.0  28725.77    4.0  39781.03    9.0  19757.50   

             feb_2     feb_3  feb_4  ...  churn_2  churn_3  churn_4  churn_5  \
customer_id                          ...                                       
169212         0.0   7895.58    3.0  ...      1.0      1.0      0.0      0.0   
174861         0.0   6155.50    3.0  ...      0.0      0.0      0.0      0.0   
198521         1.0   2824.00    3.0  ...      0.0      0.0      0.0      0.0   
206454         2.0  12095.13    6.0  ...      0.0      0.0      0.0      0.0   
247866         3.0  23120.05    4.0  ...      0.0      0.0      0.0      0.0   

             churn_6  churn_7  churn_8  churn_9  churn_10  dec_churn  
customer_id                                                           
169212           0.0      0.0      0.0      0.0       0.0        0.0  
174861           0.0      0.0      0.0      0.0       0.0        0.0  
198521           0.0      0.0      0.0      0.0       0.0        0.0  
206454           0.0      0.0      0.0      0.0       0.0        0.0  
247866           0.0      0.0      0.0      0.0       0.0        0.0  

[5 rows x 61 columns]

In [135]:
data = customer_data_2017.append(customer_data_2018)

In [136]:
data.shape

(6708, 61)

In [137]:
customer_data_2017.shape

(3354, 61)

In [138]:
customer_data_2018.shape

(3354, 61)

In [139]:
data.columns

Index(['gender', 'birth_year', 'jan_1', 'jan_2', 'jan_3', 'jan_4', 'feb_1',
       'feb_2', 'feb_3', 'feb_4', 'mar_1', 'mar_2', 'mar_3', 'mar_4', 'apr_1',
       'apr_2', 'apr_3', 'apr_4', 'may_1', 'may_2', 'may_3', 'may_4', 'jun_1',
       'jun_2', 'jun_3', 'jun_4', 'jul_1', 'jul_2', 'jul_3', 'jul_4', 'aug_1',
       'aug_2', 'aug_3', 'aug_4', 'sep_1', 'sep_2', 'sep_3', 'sep_4', 'oct_1',
       'oct_2', 'oct_3', 'oct_4', 'nov_1', 'nov_2', 'nov_3', 'nov_4', 'dec_1',
       'dec_2', 'dec_3', 'dec_4', 'churn_1', 'churn_2', 'churn_3', 'churn_4',
       'churn_5', 'churn_6', 'churn_7', 'churn_8', 'churn_9', 'churn_10',
       'dec_churn'],
      dtype='object')

In [140]:
X = data.drop('dec_churn', 1)
y = data['dec_churn']

customer_data_2019 = pd.read_csv("final2019.csv")

customer_data_2019 = customer_data_2019.drop('dec_churn', 1)
xdata = customer_data_2019.copy()
test = xdata.drop('customer_id', 1)
test_id = xdata['customer_id']

customer_data_2019 = pd.read_csv("final2019.csv", index_col =0)
customer_data_2019 = customer_data_2019.drop(rem)

customer_data_2019 = customer_data_2019.drop('dec_churn', 1)
xdata = customer_data_2019.copy()
test = xdata.copy()


In [141]:
X.shape

(6708, 60)

In [142]:
customer_data_2019.shape

(3354, 60)

In [143]:
test.shape

(3354, 60)

In [144]:
data_comp = X.append(test) #combining training and test
data_comp.shape

(10062, 60)

In [145]:
data_comp['gender'] = data_comp['gender'].map({'male': 1, 'female': 0})

In [146]:
data_comp.gender.value_counts()

1    6339
0    3723
Name: gender, dtype: int64

In [147]:
data_comp['gender'].head(10)

customer_id
169212    0
174861    0
198521    1
206454    1
247866    0
302384    1
306612    1
322933    1
325521    0
341337    1
Name: gender, dtype: int64

In [148]:
X = data_comp.iloc[:len(X)]
test = data_comp.iloc[len(X):]

In [149]:
for i in data_comp.columns:
    print(i, data_comp[i].isnull().sum())

gender 0
birth_year 0
jan_1 0
jan_2 0
jan_3 0
jan_4 0
feb_1 0
feb_2 0
feb_3 0
feb_4 0
mar_1 0
mar_2 0
mar_3 0
mar_4 0
apr_1 0
apr_2 0
apr_3 0
apr_4 0
may_1 0
may_2 0
may_3 0
may_4 0
jun_1 0
jun_2 0
jun_3 0
jun_4 0
jul_1 0
jul_2 0
jul_3 0
jul_4 0
aug_1 0
aug_2 0
aug_3 0
aug_4 0
sep_1 0
sep_2 0
sep_3 0
sep_4 0
oct_1 0
oct_2 0
oct_3 0
oct_4 0
nov_1 0
nov_2 0
nov_3 0
nov_4 0
dec_1 0
dec_2 0
dec_3 0
dec_4 0
churn_1 0
churn_2 0
churn_3 0
churn_4 0
churn_5 0
churn_6 0
churn_7 0
churn_8 0
churn_9 0
churn_10 0


In [150]:
data_comp.describe()

gender    birth_year          jan_1         jan_2          jan_3  \
count  10062.000000  10062.000000   10062.000000  10062.000000   10062.000000   
mean       0.629994   1974.996880    3419.676474      1.247466    9421.192683   
std        0.482830     12.662323    7040.158933      1.870306   15322.162582   
min        0.000000   1939.000000     -50.000000      0.000000       0.000000   
25%        0.000000   1966.000000     100.000000      0.000000     292.000000   
50%        1.000000   1977.000000     181.000000      1.000000    3754.405000   
75%        1.000000   1985.000000    3724.667500      2.000000   12089.520000   
max        1.000000   1999.000000  114409.500000     20.000000  394619.350000   

              jan_4         feb_1         feb_2          feb_3         feb_4  \
count  10062.000000  10062.000000  10062.000000   10062.000000  10062.000000   
mean       4.032200   3321.518735      1.223415    8805.162729      3.783840   
std        5.258468   6851.407849      1.821138   13932.022622      4.886617   
min        0.000000      0.000000      0.000000       0.000000      0.000000   
25%        1.000000    100.000000      0.000000     258.007500      1.000000   
50%        2.000000    118.750000      0.500000    3676.870000      2.000000   
75%        6.000000   3545.807500      2.000000   11563.920000      5.000000   
max       74.000000  92274.640000     15.000000  319197.570000     57.000000   

       ...       churn_1       churn_2       churn_3       churn_4  \
count  ...  10062.000000  10062.000000  10062.000000  10062.000000   
mean   ...      0.133572      0.116378      0.112602      0.120652   
std    ...      0.340209      0.320694      0.316121      0.325739   
min    ...      0.000000      0.000000      0.000000      0.000000   
25%    ...      0.000000      0.000000      0.000000      0.000000   
50%    ...      0.000000      0.000000      0.000000      0.000000   
75%    ...      0.000000      0.000000      0.000000      0.000000   
max    ...      1.000000      1.000000      1.000000      1.000000   

            churn_5       churn_6       churn_7       churn_8       churn_9  \
count  10062.000000  10062.000000  10062.000000  10062.000000  10062.000000   
mean       0.110813      0.107434      0.109024      0.106142      0.104751   
std        0.313916      0.309680      0.311685      0.308034      0.306247   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.000000      0.000000      0.000000      0.000000      0.000000   
50%        0.000000      0.000000      0.000000      0.000000      0.000000   
75%        0.000000      0.000000      0.000000      0.000000      0.000000   
max        1.000000      1.000000      1.000000      1.000000      1.000000   

           churn_10  
count  10062.000000  
mean       0.088352  
std        0.283821  
min        0.000000  
25%        0.000000  
50%        0.000000  
75%        0.000000  
max        1.000000  

[8 rows x 60 columns]

In [151]:
X.shape

(6708, 60)

In [152]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .2) #train test dataset splitting

In [153]:
print(data_comp.isnull().sum().sum())

0


In [154]:
y.head()

customer_id
169212    0.0
174861    0.0
198521    0.0
206454    0.0
247866    0.0
Name: dec_churn, dtype: float64

In [157]:
from sklearn.linear_model import LogisticRegression #trying different models
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
#from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score

classifiers=[['Logistic Regression :',LogisticRegression(max_iter = 1500)],
       ['Decision Tree Classification :',DecisionTreeClassifier()],
       ['Gradient Boosting Classification :', GradientBoostingClassifier()],
       ['Ada Boosting Classification :',AdaBoostClassifier()],
       ['RandomForest Classification :',RandomForestClassifier()],
       ['Extra Tree Classification :', ExtraTreesClassifier()],
       ['K-Neighbors Classification :',KNeighborsClassifier()]] # ['Gaussian Naive Bayes :',GaussianNB()]
cla_pred=[]
for name,model in classifiers:
    model=model
    model.fit(X_train,y_train)
    predictions = model.predict(X_test)
    cla_pred.append(accuracy_score(y_test,predictions))
    print(name,accuracy_score(y_test,predictions))

C:\Users\chand\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Logistic Regression : 0.9172876304023845
Decision Tree Classification : 0.8539493293591655
Gradient Boosting Classification : 0.910581222056632
Ada Boosting Classification : 0.9254843517138599
RandomForest Classification : 0.9157973174366617
Extra Tree Classification : 0.9113263785394933


C:\Users\chand\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\chand\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


K-Neighbors Classification : 0.9076005961251863


In [158]:
gbmodel = AdaBoostClassifier() #using the best parameters
gbmodel.fit(X_train, y_train)
predictions = gbmodel.predict(X_test)
print(accuracy_score(y_test,predictions))

0.9254843517138599


In [159]:
from sklearn.metrics import classification_report,confusion_matrix #evaluating the model
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))
print(accuracy_score(y_test,predictions))

[[1229    2]
 [  98   13]]
              precision    recall  f1-score   support

         0.0       0.93      1.00      0.96      1231
         1.0       0.87      0.12      0.21       111

    accuracy                           0.93      1342
   macro avg       0.90      0.56      0.58      1342
weighted avg       0.92      0.93      0.90      1342

0.9254843517138599


In [163]:
test_id

0        169212
1        174861
2        198521
3        206454
4        218494
         ...   
9995    1177848
9996    1249165
9997    1284253
9998    1308030
9999    1326394
Name: customer_id, Length: 10000, dtype: int64

In [164]:
testttt = customer_data_2019.reset_index()

In [166]:
test_id = testttt["customer_id"]

In [167]:
pred = gbmodel.predict(test)
submission = pd.DataFrame({
    'customer_id': test_id,
    'prob': pred
})
#print(submission.NEXT_MONTH_DEFAULT.value_counts())
submission.to_csv('submission_filtered.csv', index = False)

In [168]:
print(submission.prob.value_counts())

0.0    3285
1.0      69
Name: prob, dtype: int64


In [169]:
x_dnn = X.copy()
y_dnn = y.copy()

In [170]:
y_train = np.array(y_dnn)
x_train = np.array(x_dnn)

In [171]:
from sklearn.model_selection import train_test_split
xTrain, xTest, yTrain, yTest = train_test_split(x_train, y_train, test_size = 0.2, random_state = 0)

In [172]:
import tensorflow as tf

In [173]:
model = tf.keras.models.Sequential()

model.add(tf.keras.layers.Flatten())

model.add(tf.keras.layers.Dense(256,activation = tf.nn.relu))
model.add(tf.keras.layers.Dropout(0.5))
model.add(tf.keras.layers.Dense(32,activation = tf.nn.relu))
model.add(tf.keras.layers.Dense(8,activation = tf.nn.relu))

model.add(tf.keras.layers.Dense(1,activation =tf.nn.sigmoid))

model.compile(optimizer = 'adam' , loss = 'binary_crossentropy',
             metrics = ['accuracy'])
history = model.fit(xTrain,yTrain,epochs = 10,validation_split=0.05)


Train on 5097 samples, validate on 269 samples
Epoch 1/10
5097/5097 [==============================] - 1s 216us/sample - loss: 24.8399 - accuracy: 0.8966 - val_loss: 0.6310 - val_accuracy: 0.8922
Epoch 2/10
5097/5097 [==============================] - 0s 74us/sample - loss: 0.8305 - accuracy: 0.9090 - val_loss: 0.5754 - val_accuracy: 0.8922
Epoch 3/10
5097/5097 [==============================] - 0s 64us/sample - loss: 0.6323 - accuracy: 0.9088 - val_loss: 0.5318 - val_accuracy: 0.8922
Epoch 4/10
5097/5097 [==============================] - 0s 67us/sample - loss: 0.8348 - accuracy: 0.9092 - val_loss: 0.4962 - val_accuracy: 0.8922
Epoch 5/10
5097/5097 [==============================] - 0s 61us/sample - loss: 0.5048 - accuracy: 0.9092 - val_loss: 0.4669 - val_accuracy: 0.8922
Epoch 6/10
5097/5097 [==============================] - 0s 61us/sample - loss: 0.4920 - accuracy: 0.9090 - val_loss: 0.4428 - val_accuracy: 0.8922
Epoch 7/10
5097/5097 [==============================] - 0s 59us/sampl

In [174]:
test_dnn =np.array(test)

In [175]:
predictions = model.predict([test_dnn])

In [178]:
list(predictions)

[array([0.21565175], dtype=float32),
 array([0.21565175], dtype=float32),
 array([0.21565175], dtype=float32),
 array([0.21565175], dtype=float32),
 array([0.21565175], dtype=float32),
 array([0.21565175], dtype=float32),
 array([0.21565175], dtype=float32),
 array([0.21565175], dtype=float32),
 array([0.21565175], dtype=float32),
 array([0.21565175], dtype=float32),
 array([0.21565175], dtype=float32),
 array([0.21565175], dtype=float32),
 array([0.21565175], dtype=float32),
 array([0.21565175], dtype=float32),
 array([0.21565175], dtype=float32),
 array([0.21565175], dtype=float32),
 array([0.21565175], dtype=float32),
 array([0.21565175], dtype=float32),
 array([0.21565175], dtype=float32),
 array([0.21565175], dtype=float32),
 array([0.21565175], dtype=float32),
 array([0.21565175], dtype=float32),
 array([0.21565175], dtype=float32),
 array([0.21565175], dtype=float32),
 array([0.21565175], dtype=float32),
 array([0.21565175], dtype=float32),
 array([0.21565175], dtype=float32),
 

In [176]:
submission = pd.DataFrame({
    'customer_id': test_id,
    'prob': predictions
})

Exception: Data must be 1-dimensional

In [66]:
predictions.shape

(10000, 1)

In [70]:
predictions = list(float(x) for x in predictions )

In [75]:
submission.to_csv('submission_dnn.csv', index = False)